name: Go
on: [push]
jobs:
  build:
    strategy:
      matrix:
        go: [ '1.16.x', '1.17.x' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: |
        go test -v -race -bench . ./...

    - name: Build
      run: |
        cd cmd/quiwi
        go build -v
